'use strict';

// Realistic market news articles seeded for demo / restricted-network environments.
// Covers all markets: stocks, crypto, forex, commodities, indices, macro.
// Dates are staggered around today so timeAgo renders naturally.

function ago(minutes) {
  return new Date(Date.now() - minutes * 60 * 1000).toISOString();
}

const SEED = [
  // ── MACRO / FED ────────────────────────────────────────────────────────────
  { title: "Fed Minutes Signal Rate Cut Possible in September If Inflation Keeps Cooling", summary: "Federal Reserve minutes released Wednesday show officials see conditions for a rate cut building, contingent on two more months of declining CPI data. Powell emphasized the committee is 'not in a hurry' but noted risks have become 'more balanced.' Markets are pricing in a 68% chance of a September cut.", source: "MarketWatch", sourceMkt: "general", url: "https://marketwatch.com/fed-minutes-sept-cut", publishedAt: ago(18) },
  { title: "US CPI April: Inflation Cools to 2.8% YoY, Core at 3.1% — Below Expectations", summary: "April CPI came in at 2.8% year-over-year, below the 2.9% consensus. Core CPI at 3.1% also beat expectations. Shelter costs rose 0.3% MoM, the slowest pace in two years. The dollar weakened and Treasuries rallied on the print.", source: "CNBC", sourceMkt: "general", url: "https://cnbc.com/cpi-april-2026", publishedAt: ago(6) },
  { title: "US GDP Q1 Final Revision: Economy Grew 2.4%, Better Than Preliminary 2.1%", summary: "The final Q1 GDP revision showed the US economy expanded at a 2.4% annualized pace, upgraded from the preliminary 2.1% estimate. Consumer spending and business investment were the primary drivers. Recession fears fade further after the upward revision.", source: "Reuters Business", sourceMkt: "general", url: "https://reuters.com/gdp-q1-final", publishedAt: ago(54) },
  { title: "Nonfarm Payrolls Add 215K Jobs in April, Unemployment Holds at 3.9%", summary: "April jobs report came in slightly above consensus of 200K. Wage growth eased to 3.8% YoY from 4.1% previously, a development welcomed by the Fed. Healthcare and construction led gains. The report reinforces a soft-landing narrative.", source: "WSJ Markets", sourceMkt: "general", url: "https://wsj.com/jobs-april-2026", publishedAt: ago(120) },

  // ── US EQUITIES — EARNINGS & MOVERS ────────────────────────────────────────
  { title: "Nvidia Q1 Revenue Surges 78% to $47.2B, EPS Beats by 23 Cents — Stock Rallies 8%", summary: "Nvidia reported Q1 2026 revenue of $47.2B, up 78% YoY, crushing the $44.8B consensus. Data Center segment alone generated $39.1B. CEO Jensen Huang said Blackwell GPU demand 'far exceeds supply' and raised full-year guidance. Shares jumped 8% in after-hours trading.", source: "CNBC", sourceMkt: "stocks", url: "https://cnbc.com/nvda-q1-2026", publishedAt: ago(9) },
  { title: "Apple Unveils AI-Enhanced iPhone 18 Pro With On-Device LLM, Shares Up 4%", summary: "Apple's WWDC keynote revealed iPhone 18 Pro will feature a dedicated Neural Engine running a 7B parameter on-device language model, enabling offline AI tasks. Analysts at Morgan Stanley raised their price target to $265. Shares gained 4% on the news.", source: "Bloomberg", sourceMkt: "stocks", url: "https://bloomberg.com/aapl-iphone-18", publishedAt: ago(27) },
  { title: "Tesla Deliveries Miss Estimate for Third Consecutive Quarter; Stock Falls 6%", summary: "Tesla delivered 412,000 vehicles in Q1, below the 425,000 analyst consensus. The shortfall was attributed to factory retooling in Fremont and logistics delays in Europe. Elon Musk's distraction with political activities was cited by multiple analysts as a governance concern.", source: "Reuters Business", sourceMkt: "stocks", url: "https://reuters.com/tsla-deliveries-q1", publishedAt: ago(45) },
  { title: "Meta AI Monetisation Surprises: Ad Revenue Up 19%, Llama Licensing Revenue $1.2B", summary: "Meta Q1 earnings showed ad revenue growth of 19% YoY with AI-optimised ad targeting credited for the beat. The company also disclosed $1.2B in enterprise Llama 3 licensing deals. Daily active users across the family of apps hit 3.4B. Stock rose 6.5% after-hours.", source: "CNBC Markets", sourceMkt: "stocks", url: "https://cnbc.com/meta-q1-2026", publishedAt: ago(63) },
  { title: "AMD Gains Ground in AI Accelerator Market: Instinct MI400 Wins Microsoft Azure Deal", summary: "AMD announced Microsoft Azure will deploy 50,000 Instinct MI400 GPUs in its new AI training clusters, marking AMD's largest hyperscaler win to date. Analysts at JPMorgan upgraded AMD to Overweight with a $220 price target, citing accelerating data center adoption.", source: "MarketWatch", sourceMkt: "stocks", url: "https://marketwatch.com/amd-azure-deal", publishedAt: ago(81) },
  { title: "Goldman Sachs Upgrades S&P 500 Year-End Target to 6,200 on Earnings Resilience", summary: "Goldman Sachs chief equity strategist David Kostin raised the S&P 500 year-end target from 5,800 to 6,200, citing stronger-than-expected Q1 earnings season with 78% of companies beating EPS estimates. The bank sees AI capex driving durable margin expansion in tech.", source: "WSJ Markets", sourceMkt: "stocks", url: "https://wsj.com/gs-sp500-target", publishedAt: ago(97) },
  { title: "Microsoft Azure Revenue Grows 31% as AI Copilot Adoption Drives Enterprise Spending", summary: "Microsoft fiscal Q3 results showed Azure revenue growth of 31%, above the 28% consensus. CEO Satya Nadella noted more than 85% of the Fortune 500 now use Microsoft AI products. Operating income reached $28.1B. Shares rose 5.2% after-hours on the beat.", source: "CNBC Earnings", sourceMkt: "stocks", url: "https://cnbc.com/msft-q3-2026", publishedAt: ago(114) },
  { title: "Boeing 737 MAX Receives FAA Approval for Extended Range Variant; Shares Jump 5%", summary: "The FAA granted Boeing certification for the 737 MAX 10ER, the extended-range variant sought by multiple airlines for transatlantic routes. Delta and United have combined orders for 120 aircraft. The approval removes a major near-term regulatory overhang for Boeing.", source: "Reuters Business", sourceMkt: "stocks", url: "https://reuters.com/ba-737-faa", publishedAt: ago(130) },
  { title: "Palantir Secures $3.2B US Army AI Contract Extension, Stock Hits All-Time High", summary: "Palantir's AIP platform received a three-year, $3.2B extension on its AI battlefield intelligence contract with the US Army. CEO Alex Karp said this cements Palantir as 'the spine of American military AI.' PLTR shares hit an all-time high of $88.40.", source: "MarketWatch", sourceMkt: "stocks", url: "https://marketwatch.com/pltr-army-contract", publishedAt: ago(148) },
  { title: "Morgan Stanley Raises Eli Lilly Price Target to $1,000 on GLP-1 Market Dominance", summary: "Morgan Stanley analysts upgraded their Eli Lilly 12-month price target to $1,000 per share, citing GLP-1 drugs (Mounjaro, Zepbound) capturing 62% market share in the obesity and diabetes segment. They forecast Mounjaro alone reaching $28B annual revenue by 2028.", source: "CNBC Markets", sourceMkt: "stocks", url: "https://cnbc.com/lly-upgrade-ms", publishedAt: ago(165) },
  { title: "Coinbase Q1 Revenue Doubles on Crypto Bull Market; Institutional Trading Up 180%", summary: "Coinbase reported Q1 revenue of $2.4B, up 102% YoY, with net income of $1.1B. Institutional trading volume jumped 180% quarter-over-quarter. CEO Brian Armstrong noted spot Bitcoin and Ethereum ETF launches have brought in a new wave of institutional capital.", source: "The Block", sourceMkt: "stocks", url: "https://theblock.co/coinbase-q1", publishedAt: ago(182) },

  // ── CRYPTO ─────────────────────────────────────────────────────────────────
  { title: "Bitcoin Breaks $105,000 Resistance; Eyes $110K as ETF Inflows Hit Record $2.1B Weekly", summary: "Bitcoin surged past the $105,000 resistance level on high volume, with spot Bitcoin ETF inflows hitting a record $2.1B in the week. Analysts at Standard Chartered see BTC targeting $115,000 in Q2 driven by continued institutional demand and constrained post-halving supply.", source: "CoinDesk", sourceMkt: "crypto", url: "https://coindesk.com/btc-105k-breakout", publishedAt: ago(12) },
  { title: "Ethereum ETF AUM Crosses $20B as Staking Yield Drives Institutional Demand", summary: "Spot Ethereum ETFs in the US now manage $20.4B in assets, crossing the milestone amid growing institutional interest in ETH's 4.1% staking yield. BlackRock's ETHA fund alone accounts for $7.8B. Ethereum is up 12% month-to-date as the ETF demand narrative builds.", source: "CoinTelegraph", sourceMkt: "crypto", url: "https://cointelegraph.com/eth-etf-20b", publishedAt: ago(34) },
  { title: "Solana DeFi TVL Tops $18B; 'Super App' Ecosystem Drives SOL to 6-Month High", summary: "Solana's Total Value Locked in DeFi protocols reached $18B, a new record, supported by the launch of three major DEX aggregators and a new liquid staking protocol. SOL/USD rose 18% this week, hitting a 6-month high of $198 as developer activity remains elevated.", source: "Decrypt", sourceMkt: "crypto", url: "https://decrypt.co/sol-tvl-record", publishedAt: ago(52) },
  { title: "XRP Wins Final Legal Battle: SEC Appeal Denied, Ripple CEO Says 'Crypto Legal Clarity Arrives'", summary: "A US appeals court denied the SEC's attempt to appeal the Ripple decision, confirming XRP sales on secondary markets do not constitute securities transactions. XRP surged 22% on the news to $2.84. CEO Brad Garlinghouse called it a 'watershed moment for the entire crypto industry.'", source: "The Block", sourceMkt: "crypto", url: "https://theblock.co/xrp-sec-final", publishedAt: ago(70) },
  { title: "Binance Launches Regulated EU Exchange; BNB Gains 9% on Regulatory Clarity", summary: "Binance received regulatory approval to operate a fully-regulated exchange in Germany under EU's MiCA framework, a landmark move that could unlock institutional European capital. BNB rose 9% to $712 as investors bet on Binance regaining market dominance in Europe.", source: "CoinDesk", sourceMkt: "crypto", url: "https://coindesk.com/binance-eu-approved", publishedAt: ago(89) },
  { title: "Bitcoin Mining Difficulty Hits All-Time High as Hash Rate Surpasses 800 EH/s", summary: "Bitcoin's network difficulty adjusted upward by 4.2% to a new all-time high, with hash rate surpassing 800 exahashes per second for the first time. The metric signals miner confidence in sustained profitability, a historically bullish indicator for BTC price.", source: "Decrypt", sourceMkt: "crypto", url: "https://decrypt.co/btc-hashrate-ath", publishedAt: ago(107) },
  { title: "Dogecoin Surges 35% as Elon Musk Announces X Payments Integration, 'DOGE Accepted'", summary: "Dogecoin jumped 35% to $0.42 after Elon Musk announced X (formerly Twitter) will accept DOGE payments for premium subscriptions and content creator tipping, effective next quarter. On-chain activity spiked with active addresses rising 180% in 24 hours.", source: "CoinTelegraph", sourceMkt: "crypto", url: "https://cointelegraph.com/doge-x-payments", publishedAt: ago(124) },
  { title: "Avalanche Foundation Deploys $300M Ecosystem Fund; AVAX Up 14%", summary: "The Avalanche Foundation unveiled a $300M development fund targeting DeFi, gaming, and enterprise blockchain projects building on Avalanche's C-Chain. AVAX/USD rose 14% to $52 on the news, with analysts citing improving fundamentals and upcoming Durango upgrade.", source: "Decrypt", sourceMkt: "crypto", url: "https://decrypt.co/avax-ecosystem-fund", publishedAt: ago(141) },

  // ── FOREX ──────────────────────────────────────────────────────────────────
  { title: "EUR/USD Rallies to 1.1250 After ECB Signals Pause; Lagarde Cites Sticky Services Inflation", summary: "The euro strengthened to 1.1250 vs the dollar after ECB President Lagarde signalled the bank would pause its rate-cutting cycle pending further evidence of services disinflation. The ECB has cut rates three times since June 2025. EUR/USD is up 1.2% on the week.", source: "ForexLive", sourceMkt: "forex", url: "https://forexlive.com/eurusd-ecb-pause", publishedAt: ago(22) },
  { title: "USD/JPY Falls Below 148 as Bank of Japan Hints at July Rate Hike", summary: "The yen strengthened sharply, with USD/JPY breaking below the 148 handle after BoJ Governor Ueda indicated conditions may be ripe for a rate increase at the July meeting. Japan's core inflation at 2.6% exceeds the BoJ's 2% target for the 24th consecutive month.", source: "FX Street", sourceMkt: "forex", url: "https://fxstreet.com/usdjpy-boj-july", publishedAt: ago(41) },
  { title: "GBP/USD Hits 1.3450 Ahead of UK Inflation Data; Bank of England Meeting in Focus", summary: "Sterling pushed to 1.3450 against the dollar as traders positioned for a potentially hawkish Bank of England meeting next week. UK wage growth remains above 4% despite slowing overall inflation, complicating the BoE's path toward rate cuts.", source: "ForexLive", sourceMkt: "forex", url: "https://forexlive.com/gbpusd-uk-cpi", publishedAt: ago(59) },
  { title: "AUD/USD Jumps to 0.6720 as Australia Employment Surges; RBA Rate Cut Bets Fade", summary: "The Australian dollar rose sharply after Australia added 58,500 jobs in April, roughly triple the 20,000 consensus estimate. The unemployment rate held at 3.8%. Markets pushed back RBA rate cut expectations from August to November, driving AUD/USD to its highest since January.", source: "FX Street", sourceMkt: "forex", url: "https://fxstreet.com/audusd-jobs", publishedAt: ago(77) },
  { title: "Dollar Index (DXY) Slides to 102.80 on Fed Dovish Pivot Expectations", summary: "The US Dollar Index fell to 102.80, a four-week low, as soft CPI data reinforced expectations of Fed rate cuts beginning in September. Dollar weakness is broad-based, with EUR, GBP, and AUD all gaining. Gold and commodities benefit from the weaker dollar backdrop.", source: "Investing.com", sourceMkt: "forex", url: "https://investing.com/dxy-102", publishedAt: ago(93) },

  // ── COMMODITIES ────────────────────────────────────────────────────────────
  { title: "Gold Breaks $3,400/oz — Safe-Haven Demand Surges on Middle East Tensions", summary: "Spot gold surged past $3,400 per troy ounce for the first time, driven by Middle East geopolitical tensions and dollar weakness following soft US CPI. Central bank buying from China and India remains robust. Analysts at Goldman Sachs target $3,600 by year-end.", source: "Investing Commodities", sourceMkt: "commodities", url: "https://investing.com/gold-3400", publishedAt: ago(14) },
  { title: "WTI Crude Falls to $74.20 as OPEC+ Surprise Output Hike Overwhelms Demand", summary: "WTI crude oil dropped 3.4% to $74.20 per barrel after OPEC+ announced an unexpected 600,000 bpd production increase beginning June. Saudi Arabia reversed its May output cut, citing the need to defend market share amid rising non-OPEC supply from the US and Guyana.", source: "Reuters Business", sourceMkt: "commodities", url: "https://reuters.com/opec-output-hike", publishedAt: ago(32) },
  { title: "Silver Outperforms Gold, Rises 4.2% to $43.80 on Industrial Demand and Solar Boom", summary: "Silver surged 4.2% to $43.80/oz, outperforming gold on a combination of investment demand and strong industrial buying. Solar panel manufacturers have boosted silver purchasing amid record panel installations globally. The gold/silver ratio tightened to 77.6.", source: "Investing.com", sourceMkt: "commodities", url: "https://investing.com/silver-solar", publishedAt: ago(50) },
  { title: "Natural Gas Spikes 12% on Unexpected Cold Snap Forecast; Inventories Below 5-Year Average", summary: "US natural gas futures rose 12% to $3.48/MMBtu as weather models shifted toward a colder-than-expected June across the US Midwest and Northeast. EIA inventories stand 8.2% below the 5-year seasonal average, raising concerns about summer storage adequacy.", source: "MarketWatch", sourceMkt: "commodities", url: "https://marketwatch.com/natgas-spike", publishedAt: ago(68) },
  { title: "Copper Hits $11,200/tonne on China Stimulus Bets and Supply Deficit Fears", summary: "LME copper reached $11,200 per tonne, a 14-month high, as traders anticipate a major Chinese fiscal stimulus package targeting infrastructure. Chile's Codelco simultaneously flagged a 7% production shortfall due to mine disruptions, tightening the global supply outlook.", source: "Investing Commodities", sourceMkt: "commodities", url: "https://investing.com/copper-stimulus", publishedAt: ago(86) },

  // ── INDICES ────────────────────────────────────────────────────────────────
  { title: "S&P 500 Hits New All-Time High at 5,942 — AI Earnings Season Fuels the Rally", summary: "The S&P 500 closed at a new all-time high of 5,942, up 1.4% on the session, as Nvidia's blowout earnings drove broad tech buying. The index has gained 14.2% year-to-date. The Nasdaq 100 added 2.1%, while the VIX dropped to 12.3, the lowest since February.", source: "CNBC Markets", sourceMkt: "indices", url: "https://cnbc.com/sp500-ath-5942", publishedAt: ago(20) },
  { title: "VIX Falls to 12.3 — 'Fear Gauge' at Multi-Month Low as Earnings Season Outperforms", summary: "The CBOE Volatility Index (VIX) fell to 12.3, a 4-month low, signalling extreme complacency among options traders. Historically, VIX below 13 often precedes short-term market volatility as investors become over-positioned. 78% of S&P 500 companies have beaten Q1 EPS estimates.", source: "MarketWatch", sourceMkt: "indices", url: "https://marketwatch.com/vix-1230", publishedAt: ago(38) },
  { title: "Nikkei 225 Rises 1.8% as Yen Weakness Boosts Exporters; Sony and Toyota Lead", summary: "Japan's Nikkei 225 gained 1.8% to close at 38,840 as a weakening yen boosted export-oriented companies. Sony rallied 4.1% after raising its profit forecast, while Toyota added 2.7% on record-high US sales projections. Bank of Japan policy uncertainty remains the key macro risk.", source: "Reuters Business", sourceMkt: "indices", url: "https://reuters.com/nikkei-exporters", publishedAt: ago(56) },
  { title: "Hang Seng Surges 3.1% on China Stimulus Hopes; Tech Giants Lead Gains", summary: "Hong Kong's Hang Seng Index surged 3.1% to 22,450 following reports of an imminent $1 trillion Chinese fiscal stimulus package targeting technology and infrastructure. Alibaba rose 6%, Tencent gained 4.8%. The CSI 300 on the mainland added 2.4%.", source: "Reuters Business", sourceMkt: "indices", url: "https://reuters.com/hsi-china-stimulus", publishedAt: ago(74) },
  { title: "DAX Hits Record 22,800 as German Industrial Output Beats; ECB Pause Lifts Sentiment", summary: "Germany's DAX index set a new all-time high at 22,800, driven by better-than-expected April industrial output data (+1.8% MoM vs +0.6% expected) and the ECB's signal to pause rate cuts, reducing near-term uncertainty for European corporates.", source: "Investing.com", sourceMkt: "indices", url: "https://investing.com/dax-record", publishedAt: ago(92) },

  // ── SGX STOCKS ─────────────────────────────────────────────────────────────
  { title: "DBS Bank Q1 Profit Rises 8% to S$2.96B; NIM Holds at 2.13% Despite Rate Pressures", summary: "DBS Group's Q1 2026 net profit climbed 8% year-on-year to S$2.96B, slightly ahead of consensus. Net interest margin held at 2.13% as the bank successfully managed deposit repricing. CEO Piyush Gupta flagged strong loan growth in India and Indonesia. Dividend maintained at S$0.54.", source: "Business Times", sourceMkt: "stocks", url: "https://bt.sg/dbs-q1-2026", publishedAt: ago(103) },
  { title: "Singapore Airlines Reports Record Full-Year Profit of S$3.2B on Premium Travel Demand", summary: "SIA posted a record annual profit of S$3.2B for FY2026, up 11% from the prior year. Passenger load factor reached 88.1%, the highest in the airline's history. Management guided for continued double-digit revenue growth as premium cabin demand remains strong.", source: "Business Times", sourceMkt: "stocks", url: "https://bt.sg/sia-record-profit", publishedAt: ago(158) },
  { title: "Singtel Surges 6% After Announcing S$2B Share Buyback and Optus Sale Completion", summary: "Singtel shares jumped 6% after the company completed the sale of a 10% stake in Optus for A$1.8B and announced a S$2B share buyback programme. The capital return comes alongside strong Airtel India performance, which contributed S$890M in equity income for the year.", source: "Business Times", sourceMkt: "stocks", url: "https://bt.sg/singtel-buyback", publishedAt: ago(175) },

  // ── ADDITIONAL SWING-SIGNAL ARTICLES ──────────────────────────────────────
  { title: "Short Interest in Tesla Reaches 18-Month High at $16B — Largest Short Position on Record", summary: "Tesla bears have accumulated $16B in short positions, the largest on record, ahead of the next quarterly deliveries report. Short interest represents 4.9% of the float. Options market shows elevated put buying, with the 30-day implied volatility at 62%.", source: "CNBC Markets", sourceMkt: "stocks", url: "https://cnbc.com/tsla-short-interest", publishedAt: ago(200) },
  { title: "Insider Buying Alert: PLTR CEO Alex Karp Buys $12M in Shares at Open Market", summary: "SEC Form 4 filings show Palantir CEO Alex Karp purchased 150,000 shares at an average of $80.20, totalling approximately $12M, in open-market transactions over three days. Insider buying at this scale is typically considered a strong bullish signal by market practitioners.", source: "MarketWatch", sourceMkt: "stocks", url: "https://marketwatch.com/pltr-insider-buy", publishedAt: ago(215) },
  { title: "NVDA Options Activity Explodes: $2B in Calls Bought Ahead of Earnings — Largest Ever", summary: "Nvidia options activity reached a historic level with $2B in call options purchased in the three sessions prior to earnings, the largest pre-earnings options buy in market history. The most popular strike is the $1,200 call expiring next Friday. IV crush risk is extreme post-earnings.", source: "MarketWatch", sourceMkt: "stocks", url: "https://marketwatch.com/nvda-options-record", publishedAt: ago(232) },
  { title: "BTC Technical: Golden Cross Forms on Weekly Chart — Historically Signals 40%+ Rally", summary: "Bitcoin's 50-week moving average crossed above the 200-week moving average for the first time since November 2023, forming a 'Golden Cross' on the weekly chart. This pattern preceded 40%+ rallies in all previous occurrences (2019, 2020, 2023). Current price: $103,800.", source: "CoinDesk", sourceMkt: "crypto", url: "https://coindesk.com/btc-golden-cross", publishedAt: ago(248) },
  { title: "Secondary Offering: Rivian Prices $1.2B Stock Sale at $12.40, Shares Fall 8%", summary: "Rivian priced a $1.2B secondary share offering at $12.40 per share, a 7% discount to the prior day's close. The company said proceeds will fund Volkswagen joint venture ramp-up costs. Shares fell 8% on the dilution announcement, bringing RIVN's YTD decline to -32%.", source: "Reuters Business", sourceMkt: "stocks", url: "https://reuters.com/rivn-secondary", publishedAt: ago(263) },
];

// Queue of additional articles to drip-feed every poll cycle (simulates live updates)
const DRIP_QUEUE = [
  { title: "Bitcoin Spot ETF Net Inflows Hit $420M Today — BlackRock IBIT Leads", summary: "Spot Bitcoin ETF net inflows reached $420M on Friday, led by BlackRock's IBIT with $238M. Total US spot BTC ETF AUM now stands at $112B. The sustained inflow pace continues to compress available spot BTC supply on exchanges.", source: "CoinDesk", sourceMkt: "crypto", url: "https://coindesk.com/btc-etf-inflow-420m", publishedAt: null },
  { title: "FOMC: Fed Holds Rates at 4.25%-4.5%, Dots Show Two Cuts in 2026", summary: "The Federal Open Market Committee voted unanimously to hold rates at 4.25%-4.5%. The updated dot plot shows the median expectation of two 25bp cuts in 2026, both in H2. Chair Powell noted the labour market remains 'robust' but inflation progress is 'encouraging.'", source: "CNBC", sourceMkt: "general", url: "https://cnbc.com/fomc-hold-dots-2026", publishedAt: null },
  { title: "Gold Futures Hit New Record $3,450 Intraday — Geopolitical Risk Premium Expanding", summary: "COMEX gold futures briefly touched $3,450/oz intraday before settling at $3,428. Analysts attribute the move to escalating Middle East tensions and accelerating central bank diversification away from dollar-denominated assets. WGC data shows 1,136 tonnes of central bank buying in 2025.", source: "Investing.com", sourceMkt: "commodities", url: "https://investing.com/gold-3450", publishedAt: null },
  { title: "Nvidia H200 GPU Backlog Extends to 18 Months — Supply Crunch Deepens", summary: "Industry sources tell CNBC that Nvidia H200 GPU delivery times have extended to 18 months, up from 12 months in Q4 2025. TSMC's CoWoS packaging capacity, a critical bottleneck, is fully allocated through 2027. AMD sees opportunity with MI400 ramp-up but supply is also constrained.", source: "CNBC Markets", sourceMkt: "stocks", url: "https://cnbc.com/nvda-h200-backlog", publishedAt: null },
  { title: "EUR/USD Drops to 1.1180 as German Retail Sales Miss; Eurozone Growth Doubts Return", summary: "The euro pulled back to 1.1180 after German retail sales contracted 0.8% in April, well below the +0.3% forecast. Weak consumer spending in the eurozone's largest economy raises doubts about ECB's forecast of a 2026 growth rebound. EUR/USD support seen at 1.1100.", source: "ForexLive", sourceMkt: "forex", url: "https://forexlive.com/eurusd-german-retail", publishedAt: null },
  { title: "Tesla Cybertruck Production Ramp: 1,200 Units/Week Achieved, On Track for 2026 Target", summary: "Tesla confirmed Cybertruck production hit 1,200 units per week at Gigafactory Texas, on a run-rate to meet the 80,000-unit 2026 delivery target. Gross margin for Cybertruck is now positive for the first time at 8.4%. Backlog stands at 180,000 reservations.", source: "Reuters Business", sourceMkt: "stocks", url: "https://reuters.com/tsla-cybertruck-ramp", publishedAt: null },
  { title: "Ethereum Layer-2 Ecosystem Hits $35B TVL — Base, Arbitrum, Optimism Lead", summary: "The combined TVL across all Ethereum Layer-2 networks surpassed $35B for the first time. Coinbase's Base leads with $12.4B, followed by Arbitrum ($9.8B) and Optimism ($7.2B). Lower fees and faster settlement are attracting DeFi activity away from Ethereum mainnet.", source: "Decrypt", sourceMkt: "crypto", url: "https://decrypt.co/eth-l2-35b", publishedAt: null },
  { title: "WTI Oil Rebounds to $76.80 as US Strategic Reserve Drawdown Halted", summary: "WTI crude recovered to $76.80/barrel after the US Department of Energy announced it would pause Strategic Petroleum Reserve sales, removing a key source of supply overhang. OPEC+ compliance reportedly improved to 94% according to secondary source data.", source: "Reuters Business", sourceMkt: "commodities", url: "https://reuters.com/wti-spr-halt", publishedAt: null },
];

let dripIndex = 0;
function nextDrip() {
  if (dripIndex >= DRIP_QUEUE.length) dripIndex = 0;
  const a = { ...DRIP_QUEUE[dripIndex++] };
  a.publishedAt = new Date().toISOString();
  a.id = a.url;
  return a;
}

module.exports = { SEED, nextDrip };
