'use strict';
// Rebuild inventory aligned with actual clients in the orders table
// node seed_inventory.js

const { getTenantDb } = require('./lib/db/tenant');
const createInventory  = require('./lib/inventory');

const db  = getTenantDb('default');
const inv = createInventory(db);

const dr  = (i, m) => ((i * 2654435761) >>> 0) % m;
const dp  = (i, m, off = 0) => (((i * 1664525 + 1013904223) >>> 0) % m) + off;
const pick = (i, arr) => arr[dr(i * 6007, arr.length)];

const ZONES   = ['A','B','C','D','E'];
const ROWS    = Array.from({length:10}, (_,i) => String(i+1).padStart(2,'0'));
const SHELVES = ['01','02','03','04','05'];
const BINS    = ['01','02','03','04'];
const loc = i => `Zone ${pick(i*3,ZONES)}-Row ${pick(i*7,ROWS)}-Shelf ${pick(i*11,SHELVES)}-Bin ${pick(i*13,BINS)}`;

// [sku, name, category, unit, cost, sell, desc]
const CLIENTS = [

  // ── 1. ALMIGHTY — Sports Nutrition (72 SKUs) ─────────────────────────────
  { name: 'Almighty', items: [
    ['WHEY-1KG-CHC', 'Whey Protein 1kg Chocolate',     'Sports Nutrition','unit', 38, 79,  'Whey isolate 1kg, chocolate fudge'],
    ['WHEY-1KG-VAN', 'Whey Protein 1kg Vanilla',       'Sports Nutrition','unit', 38, 79,  'Whey isolate 1kg, vanilla cream'],
    ['WHEY-1KG-STW', 'Whey Protein 1kg Strawberry',    'Sports Nutrition','unit', 38, 79,  'Whey isolate 1kg, strawberry milkshake'],
    ['WHEY-1KG-COF', 'Whey Protein 1kg Coffee',        'Sports Nutrition','unit', 38, 79,  'Whey isolate 1kg, iced coffee'],
    ['WHEY-2KG-CHC', 'Whey Protein 2kg Chocolate',     'Sports Nutrition','unit', 68,139,  'Whey isolate 2kg, chocolate fudge'],
    ['WHEY-2KG-VAN', 'Whey Protein 2kg Vanilla',       'Sports Nutrition','unit', 68,139,  'Whey isolate 2kg, vanilla cream'],
    ['CASEIN-1KG',   'Casein Protein 1kg Chocolate',   'Sports Nutrition','unit', 42, 88,  'Micellar casein slow-release protein 1kg'],
    ['PLANT-PRO1K',  'Plant Protein 1kg Choc',         'Sports Nutrition','unit', 42, 88,  'Pea + rice plant protein blend 1kg'],
    ['PLANT-PRO-VAN','Plant Protein 1kg Vanilla',      'Sports Nutrition','unit', 42, 88,  'Pea + rice plant protein 1kg, vanilla'],
    ['MASS-2KG',     'Mass Gainer 2kg Chocolate',      'Sports Nutrition','unit', 55,119,  'High-calorie mass gainer 2kg'],
    ['MASS-3KG',     'Mass Gainer 3kg Chocolate',      'Sports Nutrition','unit', 78,168,  'High-calorie mass gainer 3kg'],
    ['PRE-WRK',      'Pre-Workout 300g Mixed Berry',   'Sports Nutrition','unit', 22, 59,  'Pre-workout formula 300g, mixed berry'],
    ['PRE-WRK-WTRM', 'Pre-Workout 300g Watermelon',    'Sports Nutrition','unit', 22, 59,  'Pre-workout formula 300g, watermelon'],
    ['PRE-WRK-BLU',  'Pre-Workout 300g Blue Razz',     'Sports Nutrition','unit', 22, 59,  'Pre-workout formula 300g, blue raspberry'],
    ['PRE-WRK-TRPC', 'Pre-Workout 300g Tropical',      'Sports Nutrition','unit', 22, 59,  'Pre-workout formula 300g, tropical burst'],
    ['BCAA-300',     'BCAA 300g Watermelon',           'Sports Nutrition','unit', 18, 49,  'BCAA 2:1:1 powder 300g, watermelon'],
    ['BCAA-300-MNG', 'BCAA 300g Mango Pineapple',      'Sports Nutrition','unit', 18, 49,  'BCAA 2:1:1 powder 300g, mango pineapple'],
    ['EAA-300',      'EAA Amino Acids 300g Peach',     'Sports Nutrition','unit', 20, 52,  'Essential amino acids 300g, peach'],
    ['GLUTAMINE',    'L-Glutamine 300g Unflavoured',   'Sports Nutrition','unit', 14, 38,  'L-Glutamine pure powder 300g'],
    ['CREAT-300',    'Creatine Monohydrate 300g',      'Sports Nutrition','unit', 16, 42,  'Micronised creatine monohydrate 300g'],
    ['CREAT-500',    'Creatine Monohydrate 500g',      'Sports Nutrition','unit', 24, 62,  'Micronised creatine monohydrate 500g'],
    ['HYDRATAB',     'Electrolyte Tabs 20s',           'Sports Nutrition','tube',  5, 14,  'Zero-cal electrolyte effervescent tabs, 20pk'],
    ['CAFFTAB-120',  'Caffeine 200mg 120s',            'Sports Nutrition','btl',   7, 18,  'Caffeine anhydrous 200mg, 120 tabs'],
    ['VITC-60',      'Vitamin C 1000mg 60s',           'Sports Nutrition','btl',   9, 28,  'Vitamin C 1000mg, 60 capsules'],
    ['VITD3K2-60',   'Vitamin D3+K2 60 Softgels',      'Sports Nutrition','btl',  10, 27,  'D3 5000IU + K2 100mcg, 60 softgels'],
    ['VITB-CPLX',    'Vitamin B Complex 60s',          'Sports Nutrition','btl',   7, 19,  'Full-spectrum B-complex, 60 tabs'],
    ['MULTI-30',     'Daily Multivitamin 30s',         'Sports Nutrition','btl',   7, 19,  'Complete daily multivitamin 30 tabs'],
    ['OMEGA3-90',    'Omega-3 Fish Oil 90 Softgels',   'Sports Nutrition','btl',  12, 32,  'Omega-3 1000mg, 90 softgels'],
    ['MAGNES-60',    'Magnesium Glycinate 400mg 60s',  'Sports Nutrition','btl',  10, 26,  'Magnesium glycinate 400mg, 60 caps'],
    ['ZINC-60',      'Zinc + Vitamin D 60s',           'Sports Nutrition','btl',   8, 22,  'Zinc 25mg + Vit D 1000IU, 60 caps'],
    ['COL-30S',      'Marine Collagen Sachets 30pk',   'Sports Nutrition','box',  24, 65,  'Marine collagen peptides sachets 30pk'],
    ['COLCAPS-60',   'Marine Collagen Caps 60s',       'Sports Nutrition','btl',  18, 48,  'Marine collagen peptides 500mg, 60 caps'],
    ['BIOTIN-60',    'Biotin 5000mcg 60s',             'Sports Nutrition','btl',   8, 21,  'Biotin hair & nail support, 60 caps'],
    ['CLA-90',       'CLA 1000mg 90 Softgels',         'Sports Nutrition','btl',  13, 34,  'Conjugated linoleic acid 1000mg, 90 sg'],
    ['FATBURN-60',   'Fat Burner 60 Caps',             'Sports Nutrition','btl',  16, 44,  'Thermogenic fat burner blend, 60 caps'],
    ['SLEEPAID-30',  'Magnesium Sleep Formula 30s',    'Sports Nutrition','btl',  11, 29,  'Magnesium + L-theanine sleep formula 30s'],
    ['MEALRPL-500',  'Meal Replacement Shake 500g',    'Sports Nutrition','unit', 28, 68,  'Balanced meal replacement shake 500g'],
    ['SPIRULINA',    'Organic Spirulina Powder 200g',  'Sports Nutrition','unit', 12, 32,  'Organic spirulina powder 200g'],
    ['TURMERIC-60',  'Turmeric + Black Pepper 60s',    'Sports Nutrition','btl',  10, 26,  'Turmeric + black pepper extract, 60 caps'],
    ['ASHWAGANDHA',  'Ashwagandha KSM-66 60s',         'Sports Nutrition','btl',  12, 32,  'Ashwagandha root extract KSM-66 60 caps'],
    ['IRONC-30',     'Iron + Vitamin C 30s',           'Sports Nutrition','btl',   6, 16,  'Iron bisglycinate 20mg + Vit C, 30 tabs'],
    ['PROBIO-30',    'Probiotic 30 Billion 30s',       'Sports Nutrition','btl',  14, 36,  '30 billion CFU probiotic, 8 strains, 30s'],
    ['COLLAGEN3',    'Collagen Type 1+3 60s',          'Sports Nutrition','btl',  16, 42,  'Hydrolysed collagen type 1 & 3, 60 caps'],
    ['PBAR-CHC12',   'Protein Bar Choc Peanut 12pk',   'Sports Nutrition','box',  22, 48,  'Whey protein bar 60g, choc peanut, 12pk'],
    ['PBAR-VAN12',   'Protein Bar Vanilla 12pk',       'Sports Nutrition','box',  22, 48,  'Whey protein bar 60g, vanilla, 12pk'],
    ['PBAR-BRY12',   'Protein Bar Mixed Berry 12pk',   'Sports Nutrition','box',  22, 48,  'Whey protein bar 60g, mixed berry, 12pk'],
    ['COFFEBLCK-15', 'Black Coffee Sachets 15pk',      'Sports Nutrition','box',   8, 22,  'Unsweetened instant black coffee, 15pk'],
    ['ENRGY-SNCK',   'Energy Oat Snack Balls 12pk',    'Sports Nutrition','box',  14, 36,  'Oat + nut energy snack balls, 12pk'],
    ['SHAKER-700',   'Protein Shaker 700ml Clear',     'Sports Nutrition','pcs',   4, 12,  'BPA-free shaker 700ml, flip lid, clear'],
    ['SHAKER-1L',    'Protein Shaker 1L Black',        'Sports Nutrition','pcs',   6, 15,  'BPA-free shaker 1L, black, screw cap'],
    ['PILLBOX-7',    'Weekly Pill Organiser 7-Day',    'Sports Nutrition','pcs',   4, 10,  '7-day AM/PM pill organiser, BPA-free'],
    ['GYMTOWEL',     'Microfibre Gym Towel 40x80cm',   'Sports Nutrition','pcs',   5, 13,  'Quick-dry microfibre gym towel 40x80cm'],
    ['TOTE-NUTRITION','Nutrition Insulated Tote Bag',  'Sports Nutrition','pcs',  12, 30,  'Insulated lunch tote for meal prep'],
  ]},

  // ── 2. ATHENA SCENTS — Fragrance & Home Scents (72 SKUs) ─────────────────
  { name: 'Athena Scents', items: [
    ['OUD-50',       'Oud Perfume EDP 50ml',           'Fragrance','btl',  35, 88,  'Luxury oud eau de parfum 50ml'],
    ['OUD-100',      'Oud Perfume EDP 100ml',          'Fragrance','btl',  58,148,  'Luxury oud eau de parfum 100ml'],
    ['OUD-MINI',     'Oud EDP Travel Spray 10ml',      'Fragrance','btl',  10, 28,  'Oud eau de parfum travel spray 10ml'],
    ['OUD-ATTAR',    'Oud Attar Oil Roll-On 12ml',     'Fragrance','btl',  22, 58,  'Pure oud attar oil roll-on 12ml'],
    ['ROSE-EDP',     'Rose Garden EDP 50ml',           'Fragrance','btl',  24, 65,  'Rose garden eau de parfum 50ml'],
    ['ROSE-EDP100',  'Rose Garden EDP 100ml',          'Fragrance','btl',  38,108,  'Rose garden eau de parfum 100ml'],
    ['ROSE-ATTAR',   'Rose Attar Oil Roll-On 12ml',    'Fragrance','btl',  18, 48,  'Pure rose attar roll-on oil 12ml'],
    ['LAVEND-EDP',   'Lavender Dreams EDP 50ml',       'Fragrance','btl',  22, 58,  'Lavender & musk eau de parfum 50ml'],
    ['AMBER-EDP',    'Amber Noir EDP 50ml',            'Fragrance','btl',  28, 72,  'Amber noir woody eau de parfum 50ml'],
    ['ORCHID-EDP',   'Black Orchid EDP 50ml',          'Fragrance','btl',  30, 78,  'Black orchid & vanilla EDP 50ml'],
    ['CEDAR-EDP',    'Cedarwood Musk EDP 50ml',        'Fragrance','btl',  26, 68,  'Cedarwood + white musk EDP 50ml'],
    ['JASMINE-EDP',  'Jasmine Nights EDP 50ml',        'Fragrance','btl',  24, 65,  'Jasmine & sandalwood EDP 50ml'],
    ['PEONY-EDP',    'Peony Blossom EDP 50ml',         'Fragrance','btl',  24, 65,  'Peony & white tea EDP 50ml'],
    ['MUSK-EDP',     'White Musk EDP 50ml',            'Fragrance','btl',  22, 58,  'Clean white musk eau de parfum 50ml'],
    ['ITAL-EDP',     'Italian Citrus EDP 50ml',        'Fragrance','btl',  22, 58,  'Fresh bergamot & citrus EDP 50ml'],
    ['OUD-ROSE-EDP', 'Oud Rose EDP 50ml',              'Fragrance','btl',  32, 82,  'Oud & rose fusion EDP 50ml'],
    ['GIFT-SET-A',   'Fragrance Gift Set A',           'Fragrance','set',  35, 89,  'Gift set: EDP 50ml + candle + mist'],
    ['GIFT-SET-B',   'Luxury Oud Gift Set',            'Fragrance','set',  55,138,  'Gift set: oud 100ml + attar + candle'],
    ['GIFT-SET-C',   'Floral Gift Set',                'Fragrance','set',  30, 78,  'Gift set: rose EDP + rose mist + body lotion'],
    ['CNDL-JASN',    'Jasmine Soy Candle 200g',        'Fragrance','pcs',  10, 32,  'Hand-poured soy candle, jasmine, 200g'],
    ['CNDL-ROSE',    'Rose & Oud Candle 250g',         'Fragrance','pcs',  12, 36,  'Hand-poured soy candle, rose & oud, 250g'],
    ['CNDL-LAVND',   'Lavender Soy Candle 200g',       'Fragrance','pcs',  10, 32,  'Hand-poured soy candle, lavender, 200g'],
    ['CNDL-AMBER',   'Amber & Vanilla Candle 200g',    'Fragrance','pcs',  10, 32,  'Hand-poured soy candle, amber & vanilla'],
    ['CNDL-VAN',     'Vanilla Dream Candle 200g',      'Fragrance','pcs',  10, 32,  'Hand-poured soy candle, vanilla cream'],
    ['CNDL-CEDAR',   'Cedar & Smoke Candle 200g',      'Fragrance','pcs',  10, 32,  'Hand-poured soy candle, cedar & smoke'],
    ['CNDL-PEONY',   'Peony Candle 200g',              'Fragrance','pcs',  10, 32,  'Hand-poured soy candle, peony & lily'],
    ['CNDL-XLRG',    'Large Pillar Candle Amber 400g', 'Fragrance','pcs',  18, 48,  'Luxury large soy candle, amber, 400g'],
    ['WAXMELT-6PK',  'Wax Melt Pack 6pc Assorted',     'Fragrance','pack',  6, 18,  'Soy wax melts, 6 assorted scents'],
    ['WAXMELT-OUD',  'Wax Melt Oud 6pc',               'Fragrance','pack',  7, 20,  'Oud soy wax melts, 6-pack'],
    ['REED-LMGR',    'Reed Diffuser Lemongrass 100ml', 'Fragrance','pcs',  14, 42,  'Lemongrass reed diffuser 100ml, 8 reeds'],
    ['REED-ROSE',    'Reed Diffuser Rose 100ml',       'Fragrance','pcs',  14, 42,  'Rose & geranium reed diffuser 100ml'],
    ['REED-OUD',     'Reed Diffuser Oud 100ml',        'Fragrance','pcs',  16, 48,  'Oud & sandalwood reed diffuser 100ml'],
    ['REED-LAVND',   'Reed Diffuser Lavender 100ml',   'Fragrance','pcs',  14, 42,  'Lavender reed diffuser 100ml'],
    ['REED-CEDAR',   'Reed Diffuser Cedar 100ml',      'Fragrance','pcs',  14, 42,  'Cedarwood reed diffuser 100ml'],
    ['REED-REFIL',   'Reed Diffuser Refill 100ml',     'Fragrance','btl',   8, 22,  'Fragrance refill for reed diffuser'],
    ['MIST-FLRL',    'Floral Body Mist 200ml',         'Fragrance','btl',   8, 28,  'Light floral body mist 200ml'],
    ['MIST-OUD',     'Oud Body Mist 200ml',            'Fragrance','btl',  10, 32,  'Rich oud body mist 200ml'],
    ['MIST-ROSE',    'Rose Water Body Mist 200ml',     'Fragrance','btl',   8, 28,  'Rose water refreshing body mist 200ml'],
    ['ROOM-SPRAY',   'Room Spray Linen 100ml',         'Fragrance','btl',   9, 26,  'Linen & white tea room spray 100ml'],
    ['ROOM-OUD',     'Room Spray Oud 100ml',           'Fragrance','btl',  10, 28,  'Oud & amber room spray 100ml'],
    ['PILLOW-MIST',  'Pillow Mist Lavender 100ml',     'Fragrance','btl',   7, 20,  'Relaxing lavender pillow & linen mist'],
    ['BODYLOTN',     'Rose Body Lotion 250ml',         'Fragrance','btl',  12, 34,  'Moisturising rose body lotion 250ml'],
    ['BODYLOTN-OUD', 'Oud Body Lotion 250ml',          'Fragrance','btl',  14, 38,  'Nourishing oud body lotion 250ml'],
    ['SCRUB-ROSE',   'Rose Sugar Body Scrub 250g',     'Fragrance','pcs',  10, 29,  'Exfoliating rose sugar body scrub 250g'],
    ['BATH-SALT',    'Himalayan Bath Salts Lavender',  'Fragrance','pcs',   8, 24,  'Himalayan lavender bath salts 500g'],
    ['BATH-OIL',     'Luxury Bath Oil Rose 100ml',     'Fragrance','btl',  12, 34,  'Rose & jojoba luxury bath oil 100ml'],
    ['HANDCRM-OUD',  'Oud Hand Cream 75ml',            'Fragrance','btl',   8, 24,  'Nourishing oud extract hand cream 75ml'],
    ['HANDCRM-ROSE', 'Rose Hand Cream 75ml',           'Fragrance','btl',   7, 20,  'Rose & vitamin E hand cream 75ml'],
    ['INCENSE-20',   'Natural Rose Incense Sticks 20pk','Fragrance','pack',  3, 10, 'Natural rose incense sticks, 20pk'],
    ['INCENSE-OUD',  'Oud Incense Sticks 20pk',        'Fragrance','pack',  4, 12,  'Natural oud incense sticks, 20pk'],
    ['CAR-FRGRNC',   'Luxury Oud Car Fragrance Clip',  'Fragrance','pcs',   5, 15,  'Oud car fragrance hanging clip'],
    ['CAR-ROSE',     'Rose Car Fragrance Clip',        'Fragrance','pcs',   4, 12,  'Rose car fragrance hanging clip'],
    ['SACHET-3PK',   'Scented Drawer Sachets 3pk',     'Fragrance','pack',  4, 12,  'Lavender scented drawer sachets, 3pk'],
    ['AROMA-STONES', 'Ceramic Aroma Stones Set',       'Fragrance','set',   8, 22,  'Unglazed ceramic aroma stones with EO'],
  ]},

  // ── 3. BETIME MARKETING — Lifestyle & Gadgets (72 SKUs) ──────────────────
  { name: 'Betime Marketing', items: [
    ['PILLOW-PRO',   'Memory Foam Pillow Pro Queen',   'Lifestyle','pcs',  18, 45,  'Contour memory foam pillow, queen'],
    ['PILLOW-STD',   'Memory Foam Pillow Standard',    'Lifestyle','pcs',  14, 36,  'Memory foam pillow, standard size'],
    ['NECK-PILL',    'Travel Neck Pillow U-Shape',     'Lifestyle','pcs',  10, 28,  'Memory foam U-shape travel neck pillow'],
    ['EYEMASK',      'Silk Sleep Eye Mask Blackout',   'Lifestyle','pcs',   5, 14,  'Silky blackout sleep eye mask'],
    ['EARPLG-50PR',  'Foam Earplugs 50 Pairs',         'Lifestyle','box',   4, 12,  'High-attenuation foam earplugs, 50 pairs'],
    ['HUMIDIF-300',  'USB Mini Humidifier 300ml',      'Lifestyle','pcs',  12, 32,  'USB ultrasonic mini humidifier 300ml'],
    ['HUMIDIF-500',  'Desktop Humidifier 500ml LED',   'Lifestyle','pcs',  16, 42,  'Desktop ultrasonic humidifier 500ml, LED'],
    ['AROMA-DIF',    'Aroma Diffuser LED 150ml',       'Lifestyle','pcs',  14, 36,  'Ultrasonic aroma diffuser, LED light, 150ml'],
    ['BACK-CUSHION', 'Lumbar Support Cushion Black',   'Lifestyle','pcs',  12, 32,  'Memory foam lumbar back support cushion'],
    ['LED-NIGHT',    'Touch LED Night Light USB',      'Lifestyle','pcs',   6, 18,  'Touch dimmable LED night light, USB'],
    ['LED-NIGHT-RGB','RGB LED Night Light 16 Colours', 'Lifestyle','pcs',   8, 22,  '16-colour RGB LED night light, remote'],
    ['LED-STRIP5M',  'RGB LED Strip Lights 5m',        'Lifestyle','pcs',  12, 32,  'App-controlled RGB LED strip, 5m, music sync'],
    ['LED-STRIP10M', 'RGB LED Strip Lights 10m',       'Lifestyle','pcs',  20, 52,  'App-controlled RGB LED strip, 10m'],
    ['LIGHT-CLIP',   'Flexible Clip LED Book Light',   'Lifestyle','pcs',   5, 14,  'USB flexible neck LED clip book light'],
    ['MONITOR-LGT',  'USB Monitor Backlight Strip',    'Lifestyle','pcs',   8, 22,  'USB LED bias lighting strip for monitor'],
    ['KEYBRD-LGT',   'USB LED Laptop Keyboard Light',  'Lifestyle','pcs',   6, 17,  'USB light bar for laptop keyboard'],
    ['FAN-USB',      'USB Desk Fan 6-inch 3-speed',    'Lifestyle','pcs',  10, 30,  'USB-powered 6-inch desk fan, 3-speed'],
    ['FAN-BLADELS',  'Bladeless Desk Fan 10-inch',     'Lifestyle','pcs',  28, 69,  'Quiet bladeless desk fan, 10-inch'],
    ['FAN-FLOOR',    'Pedestal Fan 16-inch 3-speed',   'Lifestyle','pcs',  38, 92,  'Adjustable pedestal fan 16-inch, 3-speed'],
    ['AIR-PURIF',    'Portable HEPA Air Purifier',     'Lifestyle','pcs',  22, 58,  'Desktop HEPA air purifier, USB, quiet mode'],
    ['CABLE-SET',    '3-in-1 Multi Charging Cable 1m', 'Lifestyle','set',   4, 12,  '3-in-1 cable: Lightning + Type-C + Micro USB'],
    ['CABLE-SET2M',  '3-in-1 Multi Charging Cable 2m', 'Lifestyle','set',   5, 14,  '3-in-1 cable 2m: Lightning + Type-C + Micro'],
    ['CABLE-USBC',   'USB-C 100W Fast Charge Cable 2m','Lifestyle','pcs',   4, 11,  'USB-C to USB-C 100W braided cable 2m'],
    ['CABLE-LGHT',   'MFi Lightning Cable 1.2m',       'Lifestyle','pcs',   4, 11,  'Apple MFi-certified lightning cable 1.2m'],
    ['PBANK-10K',    'Power Bank 10000mAh Slim',       'Lifestyle','pcs',  18, 48,  'Slim power bank 10000mAh, dual USB-A+C'],
    ['PBANK-20K',    'Power Bank 20000mAh Fast Charge','Lifestyle','pcs',  28, 72,  '20000mAh PD 22.5W fast-charge power bank'],
    ['TRAV-ADPT',    'Universal Travel Adapter 4-USB', 'Lifestyle','pcs',  10, 28,  'All-in-one travel adapter, 4 USB ports'],
    ['PLUG-WIFI',    'Smart WiFi Plug Energy Monitor', 'Lifestyle','pcs',   8, 22,  'Smart WiFi plug with energy monitoring'],
    ['PLUG-TIMER',   'Mechanical 24h Timer Plug',      'Lifestyle','pcs',   7, 19,  '24-hour mechanical timer outlet plug'],
    ['EXTN-LEAD',    'Surge Extension Lead 3-way 2m',  'Lifestyle','pcs',   8, 22,  '3-way surge-protected extension lead 2m'],
    ['WRL-CHRG15',   'Wireless Charging Pad 15W Qi',   'Lifestyle','pcs',  11, 29,  'Qi 15W fast wireless charging pad'],
    ['MASSAGE-G',    'Percussion Massage Gun Pro',     'Lifestyle','pcs',  36, 89,  'Percussion massage gun 6 heads, 3200rpm'],
    ['MASSAGE-MINI', 'Mini Percussion Massage Gun',    'Lifestyle','pcs',  20, 52,  'Portable mini massage gun, 3 heads'],
    ['MASSAGE-EYE',  'Electric Eye Massager Heated',   'Lifestyle','pcs',  16, 42,  'Heated vibrating eye massager, music'],
    ['SMRTSCALE',    'Smart Bluetooth Body Scale',     'Lifestyle','pcs',  18, 46,  'Bluetooth smart body scale, 13 body metrics'],
    ['PHONE-STAND',  'Foldable Aluminium Phone Stand', 'Lifestyle','pcs',   4, 12,  'Foldable aluminium adjustable phone stand'],
    ['PHONE-RING',   'Phone Ring Holder 360 Degree',   'Lifestyle','pcs',   2,  6,  'Metal ring grip phone holder, 360 rotate'],
    ['MOUS-PAD-XL',  'XL Desk Mat 80x40cm Black',      'Lifestyle','pcs',   7, 19,  'Extended desk mat 80x40cm, stitched edges'],
    ['WEBCAM-HD',    'Mini Clip Webcam 1080p',         'Lifestyle','pcs',  18, 46,  'Clip-on 1080p webcam, auto brightness correct'],
    ['CORD-ORG',     'Wooden Cable Organiser Box',     'Lifestyle','pcs',   9, 24,  'Wooden cable management box with divider'],
    ['CORD-CLIPS',   'Adhesive Cable Clips 20pk',      'Lifestyle','pack',  3,  8,  'Adhesive desk cable management clips, 20pk'],
    ['BEDSIDE-ORG',  'Bedside USB Charging Organiser', 'Lifestyle','pcs',  14, 36,  'Bedside caddy with 4-port USB hub'],
    ['STICKNOTE-WB', 'Reusable Sticky Whiteboard A3',  'Lifestyle','pcs',   6, 16,  'Erasable sticky whiteboard A3, 3-pack'],
    ['LOCKER-MINI',  'Mini Digital Steel Safe Lockbox','Lifestyle','pcs',  22, 56,  'Portable steel lockbox with keypad'],
    ['MAGNIFIER-10', 'Illuminated Hands-Free Magnifier','Lifestyle','pcs', 12, 30,  'LED hands-free magnifier 10x, flex neck'],
    ['MONI-RISER',   'Monitor Stand with Drawer',      'Lifestyle','pcs',  18, 46,  'Bamboo monitor stand riser with storage'],
    ['LAPTOP-STAND', 'Adjustable Aluminium Laptop Stand','Lifestyle','pcs', 16, 42, 'Aluminium laptop stand, foldable, up to 17in'],
    ['SCREEN-CLN',   'Screen Cleaning Kit Spray+Cloth','Lifestyle','set',   3,  9,  'Screen cleaning kit: 100ml spray + cloth'],
    ['CABLE-BOX',    'Cable Management Box Lid Large', 'Lifestyle','pcs',  12, 30,  'Cable management box with lid, large'],
  ]},

  // ── 4. CHALGO — Streetwear & Fashion Apparel (72 SKUs) ───────────────────
  { name: 'Chalgo', items: [
    ['POLO-PRM',     'Premium Polo Tee Unisex',        'Apparel','pcs',  18, 49,  'Cotton pique premium polo, unisex'],
    ['POLO-WHT-XS',  'Premium Polo White XS',          'Apparel','pcs',  18, 49,  'Cotton pique polo, white, XS'],
    ['POLO-WHT-S',   'Premium Polo White S',           'Apparel','pcs',  18, 49,  'Cotton pique polo, white, S'],
    ['POLO-WHT-M',   'Premium Polo White M',           'Apparel','pcs',  18, 49,  'Cotton pique polo, white, M'],
    ['POLO-WHT-L',   'Premium Polo White L',           'Apparel','pcs',  18, 49,  'Cotton pique polo, white, L'],
    ['POLO-WHT-XL',  'Premium Polo White XL',          'Apparel','pcs',  18, 49,  'Cotton pique polo, white, XL'],
    ['POLO-BLK-XS',  'Premium Polo Black XS',          'Apparel','pcs',  18, 49,  'Cotton pique polo, black, XS'],
    ['POLO-BLK-S',   'Premium Polo Black S',           'Apparel','pcs',  18, 49,  'Cotton pique polo, black, S'],
    ['POLO-BLK-M',   'Premium Polo Black M',           'Apparel','pcs',  18, 49,  'Cotton pique polo, black, M'],
    ['POLO-BLK-L',   'Premium Polo Black L',           'Apparel','pcs',  18, 49,  'Cotton pique polo, black, L'],
    ['POLO-NVY-M',   'Premium Polo Navy M',            'Apparel','pcs',  18, 49,  'Cotton pique polo, navy, M'],
    ['POLO-NVY-L',   'Premium Polo Navy L',            'Apparel','pcs',  18, 49,  'Cotton pique polo, navy, L'],
    ['POLO-SAGE-M',  'Premium Polo Sage Green M',      'Apparel','pcs',  18, 49,  'Cotton pique polo, sage green, M'],
    ['POLO-SAGE-L',  'Premium Polo Sage Green L',      'Apparel','pcs',  18, 49,  'Cotton pique polo, sage green, L'],
    ['CHAS-SHRT',    'Chaser Shorts Classic',          'Apparel','pcs',  12, 35,  'Stretch chaser shorts, elastic waist'],
    ['CHAS-BLK-S',   'Chaser Shorts Black S',          'Apparel','pcs',  12, 35,  'Stretch chaser shorts, black, S'],
    ['CHAS-BLK-M',   'Chaser Shorts Black M',          'Apparel','pcs',  12, 35,  'Stretch chaser shorts, black, M'],
    ['CHAS-BLK-L',   'Chaser Shorts Black L',          'Apparel','pcs',  12, 35,  'Stretch chaser shorts, black, L'],
    ['CHAS-GRY-M',   'Chaser Shorts Grey M',           'Apparel','pcs',  12, 35,  'Stretch chaser shorts, grey, M'],
    ['CHAS-GRY-L',   'Chaser Shorts Grey L',           'Apparel','pcs',  12, 35,  'Stretch chaser shorts, grey, L'],
    ['CHAS-KHK-M',   'Chaser Shorts Khaki M',          'Apparel','pcs',  12, 35,  'Stretch chaser shorts, khaki, M'],
    ['CHAS-BRN-M',   'Chaser Shorts Brown M',          'Apparel','pcs',  12, 35,  'Stretch chaser shorts, brown, M'],
    ['LINEN-SLM',    'Linen Slim Shirt',               'Apparel','pcs',  22, 65,  'Slim-fit linen shirt, button-down'],
    ['LINEN-WHT-S',  'Linen Shirt White S',            'Apparel','pcs',  22, 65,  'Slim-fit linen shirt, white, S'],
    ['LINEN-WHT-M',  'Linen Shirt White M',            'Apparel','pcs',  22, 65,  'Slim-fit linen shirt, white, M'],
    ['LINEN-WHT-L',  'Linen Shirt White L',            'Apparel','pcs',  22, 65,  'Slim-fit linen shirt, white, L'],
    ['LINEN-BLU-M',  'Linen Shirt Sky Blue M',         'Apparel','pcs',  22, 65,  'Slim-fit linen shirt, sky blue, M'],
    ['LINEN-SAGE-M', 'Linen Shirt Sage Green M',       'Apparel','pcs',  22, 65,  'Slim-fit linen shirt, sage green, M'],
    ['LINEN-SAND-M', 'Linen Shirt Sand M',             'Apparel','pcs',  22, 65,  'Slim-fit linen shirt, sand, M'],
    ['RIB-CROP',     'Ribbed Crop Top',                'Apparel','pcs',   9, 28,  'Ribbed cotton crop top, women, stretch'],
    ['RIB-BLK-XS',   'Ribbed Crop Top Black XS',       'Apparel','pcs',   9, 28,  'Ribbed crop top, black, XS'],
    ['RIB-BLK-S',    'Ribbed Crop Top Black S',        'Apparel','pcs',   9, 28,  'Ribbed crop top, black, S'],
    ['RIB-WHT-S',    'Ribbed Crop Top White S',        'Apparel','pcs',   9, 28,  'Ribbed crop top, white, S'],
    ['RIB-WHT-M',    'Ribbed Crop Top White M',        'Apparel','pcs',   9, 28,  'Ribbed crop top, white, M'],
    ['TANK-BLK-S',   'Muscle Tank Black S',            'Apparel','pcs',   7, 22,  'Cotton muscle tank, black, S'],
    ['TANK-BLK-M',   'Muscle Tank Black M',            'Apparel','pcs',   7, 22,  'Cotton muscle tank, black, M'],
    ['TANK-WHT-M',   'Muscle Tank White M',            'Apparel','pcs',   7, 22,  'Cotton muscle tank, white, M'],
    ['BOMBER-JKT',   'Bomber Jacket Classic',          'Apparel','pcs',  34, 89,  'Satin bomber jacket, embroidered badge'],
    ['BOMBER-BLK-M', 'Bomber Jacket Black M',          'Apparel','pcs',  34, 89,  'Satin bomber, black, M'],
    ['BOMBER-BLK-L', 'Bomber Jacket Black L',          'Apparel','pcs',  34, 89,  'Satin bomber, black, L'],
    ['BOMBER-GRN-M', 'Bomber Jacket Olive M',          'Apparel','pcs',  34, 89,  'Satin bomber, olive green, M'],
    ['BOMBER-BRN-M', 'Bomber Jacket Tan Brown M',      'Apparel','pcs',  34, 89,  'Satin bomber, tan brown, M'],
    ['JOGGER-M',     'Slim Jogger Pants M',            'Apparel','pcs',  20, 55,  'Slim tapered jogger, cotton fleece, M'],
    ['JOGGER-L',     'Slim Jogger Pants L',            'Apparel','pcs',  20, 55,  'Slim tapered jogger, cotton fleece, L'],
    ['CARGO-M',      'Cargo Pants M',                  'Apparel','pcs',  24, 62,  'Multi-pocket cargo pants, M'],
    ['CARGO-L',      'Cargo Pants L',                  'Apparel','pcs',  24, 62,  'Multi-pocket cargo pants, L'],
    ['HOODIE-GRY-M', 'Pullover Hoodie Grey M',         'Apparel','pcs',  22, 58,  'Heavyweight cotton pullover hoodie, grey, M'],
    ['HOODIE-GRY-L', 'Pullover Hoodie Grey L',         'Apparel','pcs',  22, 58,  'Heavyweight cotton pullover hoodie, grey, L'],
    ['HOODIE-BLK-M', 'Pullover Hoodie Black M',        'Apparel','pcs',  22, 58,  'Heavyweight cotton pullover hoodie, black, M'],
    ['HOODIE-BLK-L', 'Pullover Hoodie Black L',        'Apparel','pcs',  22, 58,  'Heavyweight cotton pullover hoodie, black, L'],
    ['OVRSZ-TEE-S',  'Oversized Tee Off-White S',      'Apparel','pcs',  10, 28,  'Oversized drop-shoulder tee, off-white, S'],
    ['OVRSZ-TEE-M',  'Oversized Tee Off-White M',      'Apparel','pcs',  10, 28,  'Oversized drop-shoulder tee, off-white, M'],
    ['OVRSZ-TEE-L',  'Oversized Tee Off-White L',      'Apparel','pcs',  10, 28,  'Oversized drop-shoulder tee, off-white, L'],
    ['KNIT-VEST-M',  'Knitted Vest Camel M',           'Apparel','pcs',  18, 48,  'Ribbed knit vest, camel, M'],
    ['CORD-SHRT-M',  'Corduroy Shirt Brown M',         'Apparel','pcs',  24, 62,  'Corduroy button-up shirt, brown, M'],
    ['BERET',        'Structured Wool Beret Camel',    'Apparel','pcs',   8, 22,  'Structured wool blend beret, camel'],
  ]},

  // ── 5. LZ8 — Fashion Accessories & Bags (72 SKUs) ────────────────────────
  { name: 'LZ8', items: [
    ['WALLET-LTH',   'Slim Bifold Leather Wallet',     'Accessories','pcs', 16, 45,  'Slim bifold genuine leather wallet, black'],
    ['WALLET-BRN',   'Slim Bifold Leather Wallet Tan', 'Accessories','pcs', 16, 45,  'Slim bifold genuine leather wallet, tan'],
    ['WALLET-MINI',  'RFID Card Holder Slim Wallet',   'Accessories','pcs',  9, 24,  'RFID-blocking slim card holder wallet'],
    ['WALLET-ZIP',   'Zip-Around Leather Wallet',      'Accessories','pcs', 20, 52,  'Zip-around leather wallet, 12 card slots'],
    ['PASSPRT-HLD',  'RFID Leather Passport Holder',   'Accessories','pcs', 10, 26,  'RFID leather passport cover, 4 card slots'],
    ['CAP-EMBD',     'Embroidered Baseball Cap Black', 'Accessories','pcs', 10, 28,  'Structured 6-panel embroidered cap, black'],
    ['CAP-EMBD-WHT', 'Embroidered Baseball Cap White', 'Accessories','pcs', 10, 28,  'Structured 6-panel embroidered cap, white'],
    ['CAP-EMBD-NVY', 'Embroidered Baseball Cap Navy',  'Accessories','pcs', 10, 28,  'Structured 6-panel embroidered cap, navy'],
    ['CAP-DAD',      'Washed Cotton Dad Cap',          'Accessories','pcs',  8, 22,  'Unstructured washed cotton dad cap'],
    ['CAP-BKT-BLK',  'Bucket Hat Black',               'Accessories','pcs',  9, 24,  'Reversible cotton bucket hat, black'],
    ['CAP-BKT-BEI',  'Bucket Hat Beige',               'Accessories','pcs',  9, 24,  'Reversible cotton bucket hat, beige'],
    ['BNIE-KNT',     'Ribbed Knit Slouch Beanie',      'Accessories','pcs',  6, 16,  'Ribbed knit slouch beanie, one size'],
    ['SUNGLS-POL',   'Polarized Acetate Sunglasses',   'Accessories','pcs', 22, 59,  'Polarized UV400 acetate frame sunglasses'],
    ['SUNGLS-AVT',   'Aviator Sunglasses Gold Mirror', 'Accessories','pcs', 20, 54,  'Classic aviator, gold frame, mirrored lens'],
    ['SUNGLS-RND',   'Round Retro Sunglasses',         'Accessories','pcs', 18, 48,  'Round retro frame UV400 sunglasses, black'],
    ['SUNGLS-SPT',   'Sport Wrap Sunglasses',          'Accessories','pcs', 16, 44,  'Lightweight sport wrap UV400 sunglasses'],
    ['SUNGLS-CAT',   'Cat-Eye Sunglasses Black',       'Accessories','pcs', 18, 48,  'Cat-eye UV400 sunglasses, black acetate'],
    ['TOTE-CVS',     'Heavy Canvas Tote Bag',          'Accessories','pcs', 12, 35,  'Heavy canvas tote with inner pocket'],
    ['TOTE-JUTE',    'Natural Jute Market Tote',       'Accessories','pcs',  8, 22,  'Natural jute market tote, rope handles'],
    ['CLUTCH-LTH',   'Genuine Leather Clutch Bag',     'Accessories','pcs', 22, 58,  'Genuine leather clutch, gold zip closure'],
    ['CRSBDY-SML',   'Mini Leather Crossbody Bag',     'Accessories','pcs', 24, 64,  'Mini leather crossbody, adjustable strap'],
    ['CRSBDY-MED',   'Medium Leather Crossbody',       'Accessories','pcs', 32, 82,  'Medium leather crossbody, 2 zip pockets'],
    ['BKPCK-SMT',    'Anti-theft Smart Backpack 20L',  'Accessories','pcs', 38, 95,  'Anti-theft USB-charge backpack, 20L'],
    ['PHONE-BAG',    'Phone Crossbody Bag Wrist',      'Accessories','pcs', 14, 36,  'Compact phone crossbody, two-zip, wrist loop'],
    ['PCHCLIP',      'Canvas Coin Pouch Carabiner',    'Accessories','pcs',  6, 16,  'Canvas coin pouch with carabiner clip'],
    ['BELT-LTH-BLK', 'Genuine Leather Belt Black 35mm','Accessories','pcs', 14, 38,  'Genuine leather belt 35mm, black'],
    ['BELT-LTH-BRN', 'Genuine Leather Belt Brown 35mm','Accessories','pcs', 14, 38,  'Genuine leather belt 35mm, tan brown'],
    ['BELT-CAN',     'Canvas Web Belt Pin Buckle',     'Accessories','pcs',  6, 16,  'Canvas woven web belt, pin buckle'],
    ['WATCH-CAS',    'Minimalist Casual Watch Mesh',   'Accessories','pcs', 34, 89,  'Minimalist casual watch, mesh strap, silver'],
    ['WATCH-CAS-BLK','Minimalist Casual Watch Black',  'Accessories','pcs', 34, 89,  'Minimalist casual watch, black mesh strap'],
    ['WATCH-LTH',    'Thin Dress Watch Leather Strap', 'Accessories','pcs', 38, 98,  'Thin dress watch, genuine leather strap'],
    ['WATCH-SPT',    'Multi-function Sport Watch',     'Accessories','pcs', 22, 56,  'Digital sport watch, multi-function, 5ATM'],
    ['BRCLT-LTH',    'Leather Wrap Bracelet Unisex',   'Accessories','pcs',  8, 22,  'Leather wrap bracelet, adjustable, unisex'],
    ['BRCLT-BDS',    'Natural Stone Bead Bracelet 3pk','Accessories','set',  9, 24,  'Natural stone beaded bracelet set, 3pk'],
    ['ANKLT',        'Dainty Chain Anklet Gold-tone',  'Accessories','pcs',  5, 14,  'Dainty gold-tone chain anklet'],
    ['KEYRING-LTH',  'Embossed Leather Keyring Tag',   'Accessories','pcs',  5, 13,  'Embossed genuine leather keyring tag'],
    ['KEYRING-CAR',  'Aluminium Carabiner Keyring',    'Accessories','pcs',  3,  9,  'Aluminium carabiner gate clip keyring'],
    ['LUGGTAG',      'Genuine Leather Luggage Tag',    'Accessories','pcs',  7, 18,  'Leather luggage tag with card window'],
    ['SILK-SCRCHIE', 'Mulberry Silk Scrunchies 5pk',   'Accessories','set',  5, 14,  'Mulberry silk hair scrunchies, 5pk mixed'],
    ['HAIRCLIP-SET', 'Matte Acetate Hair Claws 4pk',   'Accessories','set',  4, 12,  'Matte acetate hair claw clips, 4 sizes'],
    ['MIRR-CMPCT',   'Round Compact Mirror 5x',        'Accessories','pcs',  4, 11,  'Rose-gold compact mirror, double-sided 5x'],
    ['SOCK-ANKLE3',  'LZ8 Branded Ankle Socks 3pk',    'Accessories','set',  4, 12,  'Cotton ankle socks, LZ8 branded, 3pk'],
    ['GLOVES-LTH',   'Leather Touchscreen Gloves M-L', 'Accessories','pcs', 12, 32,  'Genuine leather touchscreen gloves, M-L'],
    ['SCARFKNIT',    'Chunky Knit Infinity Scarf',     'Accessories','pcs',  9, 24,  'Chunky knit infinity scarf, neutral tones'],
    ['BRLT-CUFF',    'Stainless Steel Cuff Bracelet',  'Accessories','pcs',  8, 22,  'Brushed stainless steel cuff bracelet'],
    ['RING-SLV',     'Sterling Silver Stackable Ring', 'Accessories','pcs',  6, 18,  'Sterling silver thin stackable ring, US6-8'],
    ['EAR-STUDS',    'Gold-tone Stud Earrings Set 6pk','Accessories','set',  7, 19,  'Gold-tone geometric stud earrings, 6 pairs'],
    ['HOOPS',        'Mini Gold Hoop Earrings Pair',   'Accessories','pair', 6, 16,  'Minimalist 14mm gold-tone hoop earrings'],
    ['NECKLACE-BRS', 'Dainty Bar Necklace Gold',       'Accessories','pcs',  7, 19,  'Dainty gold-tone bar pendant necklace'],
    ['CARD-HLDR',    'Magnetic Card Holder Phone Stick','Accessories','pcs',  4, 10, 'Adhesive magnetic card holder for phone back'],
    ['SPRTS-BAG',    'Mini Draw-String Gym Bag',       'Accessories','pcs',  6, 15,  'Lightweight polyester draw-string bag, LZ8'],
    ['TOTEBAG-YLLW', 'Canvas Tote Bag Yellow',         'Accessories','pcs', 10, 28,  'Heavy canvas tote, sunshine yellow'],
    ['TOTEBAG-GRN',  'Canvas Tote Bag Sage Green',     'Accessories','pcs', 10, 28,  'Heavy canvas tote, sage green'],
  ]},

  // ── 6. SIMPLYTOY — Toys & Games (72 SKUs) ────────────────────────────────
  { name: 'SimplyToy', items: [
    ['BLCK-500',     'Building Blocks 500pcs Classic', 'Toys & Games','set', 16, 45,  'Compatible building blocks 500pcs, classic'],
    ['BLCK-1000',    'Building Blocks 1000pcs',        'Toys & Games','set', 28, 72,  'Compatible building blocks 1000pcs'],
    ['BLCK-CITY',    'City Skyline Blocks Set 680pcs', 'Toys & Games','set', 38, 95,  'City skyline building blocks, 680pcs'],
    ['BLCK-SPACE',   'Space Explorer Blocks 450pcs',   'Toys & Games','set', 32, 82,  'Space-themed building blocks, 450pcs'],
    ['BLCK-CASTLE',  'Medieval Castle Blocks 820pcs',  'Toys & Games','set', 48,118,  'Medieval castle building blocks, 820pcs'],
    ['PUZZLE-500',   '500pc Jigsaw Puzzle Animals',    'Toys & Games','pcs',  8, 22,  '500-piece jigsaw puzzle, animal art'],
    ['PUZZLE-1K',    '1000pc Jigsaw Puzzle Landscape', 'Toys & Games','pcs', 12, 35,  '1000-piece jigsaw puzzle, landscape art'],
    ['PUZZLE-2K',    '2000pc Jigsaw Puzzle World Map', 'Toys & Games','pcs', 18, 48,  '2000-piece jigsaw puzzle, world map'],
    ['PUZZLE-3D',    '3D Crystal Puzzle Globe 96pcs',  'Toys & Games','pcs', 10, 28,  '3D crystal ball puzzle, 96 pieces'],
    ['PUZZLE-GLOW',  'Glow-in-Dark Puzzle 1000pc',     'Toys & Games','pcs', 14, 38,  'Glow-in-the-dark jigsaw puzzle, 1000pcs'],
    ['PUZZLE-FLOOR', 'Giant Floor Puzzle Kids 36pc',   'Toys & Games','pcs',  8, 22,  'Jumbo floor puzzle for kids, 36pc, 90x60cm'],
    ['RC-TRUCK',     'RC Monster Truck 1:16 2.4GHz',   'Toys & Games','pcs', 28, 69,  '1:16 scale RC monster truck, 2.4GHz, USB'],
    ['RC-CAR',       'RC Drift Sports Car 1:18',       'Toys & Games','pcs', 22, 55,  '1:18 RC drift car, 2.4GHz, USB charge'],
    ['RC-HELI',      'Mini Indoor RC Helicopter',      'Toys & Games','pcs', 18, 46,  '3-channel gyro-stabilised mini RC helicopter'],
    ['DRONE-MINI',   'Foldable Mini Drone 720p',       'Toys & Games','pcs', 24, 62,  'Foldable mini drone with 720p camera'],
    ['RC-BOAT',      'RC Speed Boat Water Toy',        'Toys & Games','pcs', 18, 46,  '2.4GHz RC speed boat for pool or lake'],
    ['RC-TANK',      'RC Battle Tank 1:16',            'Toys & Games','pcs', 22, 55,  '1:16 RC battle tank with BB shooting'],
    ['PLUSH-BEAR',   'Plush Teddy Bear 40cm',          'Toys & Games','pcs', 18, 55,  'Ultra-soft plush teddy bear, 40cm, brown'],
    ['PLUSH-BEAR-W', 'Plush Teddy Bear White 40cm',    'Toys & Games','pcs', 18, 55,  'Ultra-soft plush teddy bear, 40cm, white'],
    ['PLUSH-BUNNY',  'Plush Bunny Rabbit 30cm',        'Toys & Games','pcs', 14, 42,  'Soft plush bunny rabbit, 30cm, white'],
    ['PLUSH-UNIC',   'Rainbow Light-Up Unicorn 45cm',  'Toys & Games','pcs', 20, 58,  'Rainbow plush unicorn, 45cm, LED light-up'],
    ['PLUSH-DINO',   'Soft Plush Dinosaur Set 6pc',    'Toys & Games','set', 16, 44,  'Soft plush dinosaur figures, 6-piece set'],
    ['PLUSH-SLTH',   'Giant Sloth Plush 50cm',         'Toys & Games','pcs', 22, 58,  'Giant ultra-soft sloth plush toy, 50cm'],
    ['PLUSH-AXLT',   'Axolotl Plush Toy 30cm',         'Toys & Games','pcs', 14, 38,  'Soft squishy axolotl plush, pink, 30cm'],
    ['MONO-GAME',    'Monopoly Classic Board Game',    'Toys & Games','pcs', 20, 49,  'Classic Monopoly family board game'],
    ['CHESS',        'Premium Wooden Chess Set',       'Toys & Games','set', 22, 58,  'Wooden chess set with folding board 38cm'],
    ['SCRABBLE',     'Scrabble Classic Word Game',     'Toys & Games','pcs', 18, 46,  'Classic Scrabble family word game'],
    ['UNO-CARD',     'UNO Card Game 112 Cards',        'Toys & Games','pcs',  6, 16,  'UNO classic card game, 112 cards'],
    ['JENGA',        'Jenga Classic Block Tower',      'Toys & Games','pcs', 12, 32,  'Classic hardwood Jenga block tower'],
    ['SNAKES-LADR',  'Snakes & Ladders Giant Floor',   'Toys & Games','pcs', 14, 36,  'Giant floor snakes & ladders, 2m x 2m'],
    ['CONNECT4',     'Connect 4 Strategy Game',        'Toys & Games','pcs', 12, 30,  'Classic Connect 4 two-player strategy game'],
    ['BATTLESHIP',   'Battleship Game Classic',        'Toys & Games','pcs', 14, 36,  'Classic Battleship naval strategy game'],
    ['CRAYONS-64',   'Non-toxic Crayons 64 Colours',   'Toys & Games','box',  6, 16,  'Washable non-toxic crayons, 64 colours'],
    ['PAINTSET-36',  'Watercolour Paint Set 36',       'Toys & Games','set', 12, 32,  'Watercolour set, 36 colours with brush'],
    ['ARTSET-KDS',   'Kids All-in-One Art Kit 180pc',  'Toys & Games','set', 18, 46,  'Kids art kit, 180 pieces assorted'],
    ['SCIENCE-KIT',  'Kids Science Lab Kit 30 Projects','Toys & Games','set', 22, 56, 'Kids science experiment kit, 30 projects'],
    ['SLIME-KIT',    'DIY Slime Making Kit 8 Colours', 'Toys & Games','set', 10, 26,  'Slime kit, 8 colours + glitter + activator'],
    ['CLAY-KIT',     'Air-Dry Clay Set 12 Colours',    'Toys & Games','set',  8, 22,  'Air-dry modelling clay, 12 colours, tools'],
    ['DOLL-FASH',    'Fashion Doll with 3 Outfits 30cm','Toys & Games','pcs',16, 42,  'Fashion doll 30cm, 3 outfit changes'],
    ['DOLL-HOUS',    'Wooden 3-Storey Doll House',     'Toys & Games','set', 48,118,  'Wooden doll house, 3-storey + furniture'],
    ['TOOLSET-KD',   'Kids Role-Play Tool Set 18pc',   'Toys & Games','set', 14, 36,  'Kids role-play tool set, 18 pieces'],
    ['KITCHEN-KD',   'Kids Kitchen Play Set 25pc',     'Toys & Games','set', 22, 56,  'Kids kitchen playset, 25 accessories'],
    ['DOCTR-KIT',    'Kids Doctor Kit 12pc',           'Toys & Games','set', 12, 30,  'Kids role-play doctor kit, 12 pieces'],
    ['KITE',         'Diamond Kite 90cm with String',  'Toys & Games','pcs', 10, 26,  'Easy-fly diamond kite, 100m string'],
    ['SKIP-ROPE',    'Kids Adjustable Skipping Rope',  'Toys & Games','pcs',  4, 12,  'Adjustable PVC skipping rope, kids 3-8y'],
    ['BUBBLE-GUN',   'Electric Bubble Blower Gun',     'Toys & Games','pcs',  8, 22,  'Automatic electric bubble gun + solution'],
    ['SAND-SET',     'Kinetic Sand 1kg with Moulds',   'Toys & Games','set', 12, 32,  'Kinetic sand 1kg, 5 colours, moulds'],
    ['WATERBOMB',    'Self-Tying Water Balloons 500pk', 'Toys & Games','pack', 4, 10, 'Self-tying water balloons, 500pk'],
    ['YO-YO',        'Ball-Bearing Professional Yo-Yo','Toys & Games','pcs',  9, 24,  'Metal professional yo-yo, ball bearing'],
    ['FRISBEE',      'Pro Disc Frisbee 175g',          'Toys & Games','pcs',  6, 15,  'Official weight pro frisbee disc, 175g'],
    ['BADMINTON',    'Badminton Set 4-Player',         'Toys & Games','set', 14, 36,  'Badminton set, 4 rackets + 3 shuttles + net'],
  ]},

  // ── 7. SMILEFAM — Oral Care & Dental Wellness (72 SKUs) ──────────────────
  { name: 'SmileFam', items: [
    ['ELEC-BRUSH',   'Electric Toothbrush Pro 2-mode', 'Oral Care','pcs', 24, 59.90,'Rechargeable electric toothbrush, 2 modes'],
    ['SONIC-PRO2',   'Sonic Toothbrush Pro Plus 5-mode','Oral Care','pcs', 32, 78,  'Pro sonic 5-mode, 40k VPM, UV sanitiser lid'],
    ['ELEC-KIDS',    'Kids Sonic Toothbrush Timer',    'Oral Care','pcs', 16, 38,  'Kids sonic toothbrush, 2-min smart timer'],
    ['SONIC-TRAVL',  'Travel Sonic Toothbrush USB',    'Oral Care','pcs', 20, 49,  'Travel sonic toothbrush, USB charge, slim'],
    ['BRUSH-HEAD4',  'Replacement Brush Heads 4pk',    'Oral Care','pack', 8, 22,  'Compatible replacement brush heads, 4pk'],
    ['BRUSH-HEAD8',  'Replacement Brush Heads 8pk',    'Oral Care','pack',14, 36,  'Compatible replacement brush heads, 8pk'],
    ['BRUSH-ULTRSFT','Ultra Soft Manual Toothbrush 4pk','Oral Care','set', 4, 12,  'Ultra-soft bristle manual toothbrush, 4pk'],
    ['FAM-TSET',     'Family Travel Toothbrush Set 4', 'Oral Care','set',  8, 24.90,'Family travel toothbrush set, 4 brushes'],
    ['KIDS-BRUSH',   'Kids Character Toothbrush 4pk',  'Oral Care','set',  5, 14.90,'Kids character toothbrush set, 4-pack'],
    ['KIDS-BRUSH-2', 'Kids Dino Toothbrush Set 3pk',   'Oral Care','set',  4, 12,  'Dino-themed kids toothbrush set, 3pk'],
    ['TRVL-CASE',    'Ventilated Toothbrush Travel Case','Oral Care','pcs', 3,  8,  'Ventilated travel toothbrush case'],
    ['BRUSH-SANITIZ','UV Toothbrush Sanitiser Box',    'Oral Care','pcs', 12, 30,  'USB UV-C toothbrush sanitiser, holds 4 heads'],
    ['TOOTHPSTE-W',  'Charcoal Whitening Toothpaste',  'Oral Care','tube', 4, 11.90,'Activated charcoal whitening toothpaste 120g'],
    ['TOOTHPSTE-S',  'Sensitive Gum Toothpaste 120g',  'Oral Care','tube', 3.5,10.90,'Gentle sensitive gum protection toothpaste'],
    ['TOOTHPSTE-K',  'Kids Strawberry Toothpaste 75g', 'Oral Care','tube', 3,  8.90,'Fluoride kids toothpaste, strawberry, 75g'],
    ['TOOTHPSTE-N',  'Natural Herbal Toothpaste 100g', 'Oral Care','tube', 4, 11.90,'Herbal blend natural toothpaste 100g'],
    ['TOOTHPSTE-F',  'Fluoride-Free Whitening Paste',  'Oral Care','tube', 4, 11.90,'Fluoride-free natural whitening toothpaste'],
    ['TOOTH-WMTN',   'Whitening Mousse Non-Peroxide',  'Oral Care','pcs',  8, 22,  'Non-peroxide whitening mousse 50ml, mint'],
    ['WHTNG-KIT',    'LED Teeth Whitening Kit 6 Shades','Oral Care','set', 18, 49,  'LED whitening kit with gel trays, 6 shades'],
    ['WHTNG-STRIPS', 'Teeth Whitening Strips 28-day',  'Oral Care','pack',12, 32,  '28-day teeth whitening strips, enamel safe'],
    ['WHTNG-PEN',    'Teeth Whitening Pen',            'Oral Care','pcs',  6, 16,  'On-the-go whitening pen, 2ml, mint'],
    ['OILPULL',      'Coconut Oil Pulling Mouthwash',  'Oral Care','btl',  8, 22,  'Coconut oil pulling mouthwash, mint, 250ml'],
    ['MTHWSH-MNT',   'Antiseptic Mouthwash Spearmint', 'Oral Care','btl',  6, 16,  'Antiseptic mouthwash spearmint 500ml'],
    ['MTHWSH-FRSH',  'Alcohol-Free Fresh Mouthwash',   'Oral Care','btl',  6, 16,  'Alcohol-free fresh breath mouthwash 500ml'],
    ['MTHWSH-KIDS',  'Kids Bubblegum Mouthwash 300ml', 'Oral Care','btl',  4.5,12,  'Alcohol-free kids mouthwash, bubblegum'],
    ['MTHWSH-WHTN',  'Whitening Mouthwash 500ml',      'Oral Care','btl',  7, 18,  'Enamel-protect whitening mouthwash 500ml'],
    ['DENT-FLOSS',   'Mint Dental Floss 50m 2pk',      'Oral Care','pack', 3,  9.90,'Mint dental floss 50m, pack of 2'],
    ['FLOSS-CHARCO', 'Charcoal Floss 50m',             'Oral Care','pack', 3.5,9.90,'Activated charcoal mint floss 50m'],
    ['FLOSS-PICK',   'Mint Dental Floss Picks 100pk',  'Oral Care','pack', 3,  8.90,'Mint-flavoured floss picks, 100pk'],
    ['FLOSS-PICK2',  'Bamboo Floss Picks 50pk',        'Oral Care','pack', 2.5, 7.90,'Compostable bamboo floss picks, 50pk'],
    ['CHARCL-FLO',   'Charcoal Floss Picks 60pk',      'Oral Care','pack', 3.5,10,  'Activated charcoal floss picks, 60pk'],
    ['INTERDENT-8',  'Interdental Brushes ISO-2 8pk',  'Oral Care','pack', 3.5, 9.90,'Interdental brushes ISO size 2, 8pk'],
    ['INTERDENT-4',  'Interdental Brushes Variety 12pk','Oral Care','pack', 4, 10.90,'Variety interdental brush set, 12pk'],
    ['WFLOSS-200',   'Cordless Water Flosser 200ml',   'Oral Care','pcs', 22, 56,  'Cordless water flosser, 3 tips, 200ml'],
    ['WFLOSS-500',   'Desktop Water Flosser 500ml',    'Oral Care','pcs', 32, 78,  'Desktop water flosser, 10 settings, 500ml'],
    ['TNGSCRAP-2PK', 'Stainless Tongue Scraper 2pk',   'Oral Care','pack', 4.5,12,  'Stainless steel tongue scraper, 2pk'],
    ['GUMBRUSH',     'Gum Stimulator + Interdental',   'Oral Care','pcs',  4, 11,  'Gum stimulator with interdental brush'],
    ['RETAINR-BOX',  'Retainer & Aligner Storage Case','Oral Care','pcs',  3,  8,  'Vented retainer/aligner storage case'],
    ['RETAINR-CLN',  'Retainer Cleaning Tablets 60pk', 'Oral Care','pack', 5, 14,  'Effervescent retainer cleaning tablets, 60pk'],
    ['NIGHTGRD',     'Mouldable Night Guard Grinding', 'Oral Care','pcs', 10, 28,  'Mouldable night guard for teeth grinding'],
    ['NIGHTGRD-PRO', 'Pro Custom Night Guard Kit',     'Oral Care','pcs', 16, 42,  'Professional-grade mouldable night guard kit'],
    ['SNORE-STRIP',  'Nasal Strips Better Breathing 30pk','Oral Care','pack', 5, 14, 'Drug-free nasal strips, 30-pack'],
    ['SMILESET',     'SmileFam Complete Care Kit',     'Oral Care','set', 28, 72,  'Kit: toothbrush + paste + floss + mouthwash'],
    ['KIDS-SMILES',  'Kids Smile Starter Kit',         'Oral Care','set', 14, 36,  'Kids kit: toothbrush + paste + floss picks'],
    ['TRAVEL-SMILES','Travel Oral Care Kit 5pc',       'Oral Care','set', 10, 26,  'Travel kit: brush + paste + floss + case'],
    ['TOOTHPSTE-3PK','Whitening Toothpaste 3pk Bundle','Oral Care','set', 10, 28,  'Charcoal whitening toothpaste bundle, 3pk'],
    ['GUM-CARE-SET', 'Gum Health Bundle',              'Oral Care','set', 16, 42,  'Bundle: sensitive paste + gum mouthwash + flosser'],
    ['FRESHMINT-KIT','Fresh Breath Kit',               'Oral Care','set', 12, 32,  'Bundle: mouthwash + tongue scraper + floss picks'],
  ]},
];

// ── Seed ─────────────────────────────────────────────────────────────────────
inv.getAll().forEach(r => inv.remove(r.sku));

let seq = 1, imported = 0, skipped = 0;
for (const client of CLIENTS) {
  for (const row of client.items) {
    const [sku, name, category, unit, cost, sell, desc] = row;
    const stockQty = dp(seq * 17, 220, 5);
    try {
      inv.upsert({
        sku, name, category,
        location:      loc(seq),
        unit,
        stock_qty:     stockQty,
        reserved_qty:  dr(seq * 29, Math.max(1, Math.floor(stockQty * 0.12))),
        reorder_point: dp(seq * 5, 15, 5),
        cost_price:    cost,
        sell_price:    sell,
        description:   `[${client.name}] ${desc}`,
      });
      imported++;
    } catch (e) {
      console.error('SKIP', sku, e.message);
      skipped++;
    }
    seq++;
  }
}

console.log(`\nDone — ${imported} items seeded across ${CLIENTS.length} clients`);
if (skipped) console.log(`       ${skipped} skipped`);
const all = db.prepare('SELECT * FROM inventory').all();
console.log(`Total in DB: ${all.length}\n`);
for (const c of CLIENTS) {
  const n = db.prepare("SELECT COUNT(*) as cnt FROM inventory WHERE description LIKE ?").get(`[${c.name}]%`).cnt;
  console.log(`  ${c.name.padEnd(22)} ${String(n).padStart(3)} SKUs`);
}
